language: node_js
node_js:
  - "12"
dist: trusty
sudo: required
os: linux

branches:
  only:
    - master

before_script:
  - npm install

script:
  - ng build --prod --base-href https://skcraft.herokuapp.com/

deploy:
- provider: heroku
  edge: true
  api_key: $HEROKU_API_KEY
  cleanup: true
  app: skcraft
  on:
    branch: master
- provider: heroku
  edge: true
  api_key: $HEROKU_API_KEY
  cleanup: false
  app: skcraft-dev
  on:
    branch: dev