language: node_js
node_js:
  - "12"
dist: trusty
sudo: required

branches:
  only:
    - master

before_script:
  - npm install

script:
  - ng build --prod --base-href https://skcraft.herokuapp.com/

deploy:
  provider: heroku
  edge: true
  api_key: $HEROKU_API_KEY
  skip_cleanup: true
  app: skcraft
  on:
    branch: master